// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usersGetNameByID.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getNameByID = `-- name: GetNameByID :one
SELECT name
FROM users
WHERE ID = $1
`

func (q *Queries) GetNameByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getNameByID, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
